export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_AUTHENTICATE = "SET_AUTHENTICATE";
export const SET_DIRECTION = "SET_DIRECTION";
export const SET_PENDING_REQUESTS = "SET_PENDING_REQUESTS";
export const SET_TITLE = "SET_TITLE";
export const SET_IS_MOBILE = "SET_IS_MOBILE";
export const SET_BUTTON_BAR = "SET_BUTTON_BAR";
